trigger:
    - "*"

jobs:
    - job: snapshot
      timeoutInMinutes: 0
      pool:
          vmImage: vs2017-win2016
      variables:
          VAGRANT: C:\HashiCorp\Vagrant\bin\vagrant.exe
      strategy:
          maxParallel: 10
          matrix:
            msvc12:
                MSVC_VER: 12
      steps:
          - powershell: |
                Install-WindowsFeature -Name Hyper-V -IncludeManagementTools
          - script: |
                @echo on
                choco install -y virtualbox
                refreshenv
          - script: | 
                @echo on
                choco install -y vagrant
                refreshenv
          - script: | 
                %VAGRANT% plugin install vagrant-reload
          - script: |
                @echo on
                mkdir foo
                cd foo
                %VAGRANT% init hashicorp/precise64
                %VAGRANT% up
